// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * CategoryCreate
 */
export type CategoryCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CategoryRead
 */
export type CategoryRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Official
     */
    is_official: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CategoryUpdate
 */
export type CategoryUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ExperimentCreate
 */
export type ExperimentCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Steps
     */
    steps?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Graphical Model
     */
    graphical_model?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ExperimentRead
 */
export type ExperimentRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Steps
     */
    steps?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Graphical Model
     */
    graphical_model?: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ExperimentUpdate
 */
export type ExperimentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Steps
     */
    steps?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Graphical Model
     */
    graphical_model?: {
        [key: string]: unknown;
    } | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Provider
     */
    provider: string;
    /**
     * Graphical Model
     */
    graphical_model?: {
        [key: string]: unknown;
    } | null;
    /**
     * Category Id
     */
    category_id: string;
};

/**
 * TaskRead
 */
export type TaskRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Provider
     */
    provider: string;
    /**
     * Graphical Model
     */
    graphical_model?: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     */
    id: string;
    /**
     * Category Id
     */
    category_id: string;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Is Official
     */
    is_official: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TaskUpdate
 */
export type TaskUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Provider
     */
    provider?: string | null;
    /**
     * Graphical Model
     */
    graphical_model?: {
        [key: string]: unknown;
    } | null;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Display Name
     */
    display_name: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WorkflowCreate
 */
export type WorkflowCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Graphical Model
     */
    graphical_model?: {
        [key: string]: unknown;
    } | null;
};

/**
 * WorkflowRead
 */
export type WorkflowRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Graphical Model
     */
    graphical_model?: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * WorkflowUpdate
 */
export type WorkflowUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Graphical Model
     */
    graphical_model?: {
        [key: string]: unknown;
    } | null;
};

export type HealthcheckHealthzGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthcheckHealthzGetResponses = {
    /**
     * Response Healthcheck Healthz Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthcheckHealthzGetResponse = HealthcheckHealthzGetResponses[keyof HealthcheckHealthzGetResponses];

export type ReadCurrentUserUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type ReadCurrentUserUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type ReadCurrentUserUsersMeGetResponse = ReadCurrentUserUsersMeGetResponses[keyof ReadCurrentUserUsersMeGetResponses];

export type ListCategoriesCategoriesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type ListCategoriesCategoriesGetResponses = {
    /**
     * Response List Categories Categories Get
     *
     * Successful Response
     */
    200: Array<CategoryRead>;
};

export type ListCategoriesCategoriesGetResponse = ListCategoriesCategoriesGetResponses[keyof ListCategoriesCategoriesGetResponses];

export type CreateCategoryCategoriesPostData = {
    body: CategoryCreate;
    path?: never;
    query?: never;
    url: '/categories';
};

export type CreateCategoryCategoriesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCategoryCategoriesPostError = CreateCategoryCategoriesPostErrors[keyof CreateCategoryCategoriesPostErrors];

export type CreateCategoryCategoriesPostResponses = {
    /**
     * Successful Response
     */
    201: CategoryRead;
};

export type CreateCategoryCategoriesPostResponse = CreateCategoryCategoriesPostResponses[keyof CreateCategoryCategoriesPostResponses];

export type DeleteCategoryCategoriesCategoryIdDeleteData = {
    body?: never;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/categories/{category_id}';
};

export type DeleteCategoryCategoriesCategoryIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCategoryCategoriesCategoryIdDeleteError = DeleteCategoryCategoriesCategoryIdDeleteErrors[keyof DeleteCategoryCategoriesCategoryIdDeleteErrors];

export type DeleteCategoryCategoriesCategoryIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCategoryCategoriesCategoryIdDeleteResponse = DeleteCategoryCategoriesCategoryIdDeleteResponses[keyof DeleteCategoryCategoriesCategoryIdDeleteResponses];

export type ReadCategoryCategoriesCategoryIdGetData = {
    body?: never;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/categories/{category_id}';
};

export type ReadCategoryCategoriesCategoryIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadCategoryCategoriesCategoryIdGetError = ReadCategoryCategoriesCategoryIdGetErrors[keyof ReadCategoryCategoriesCategoryIdGetErrors];

export type ReadCategoryCategoriesCategoryIdGetResponses = {
    /**
     * Successful Response
     */
    200: CategoryRead;
};

export type ReadCategoryCategoriesCategoryIdGetResponse = ReadCategoryCategoriesCategoryIdGetResponses[keyof ReadCategoryCategoriesCategoryIdGetResponses];

export type UpdateCategoryCategoriesCategoryIdPatchData = {
    body: CategoryUpdate;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/categories/{category_id}';
};

export type UpdateCategoryCategoriesCategoryIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCategoryCategoriesCategoryIdPatchError = UpdateCategoryCategoriesCategoryIdPatchErrors[keyof UpdateCategoryCategoriesCategoryIdPatchErrors];

export type UpdateCategoryCategoriesCategoryIdPatchResponses = {
    /**
     * Successful Response
     */
    200: CategoryRead;
};

export type UpdateCategoryCategoriesCategoryIdPatchResponse = UpdateCategoryCategoriesCategoryIdPatchResponses[keyof UpdateCategoryCategoriesCategoryIdPatchResponses];

export type ListTasksTasksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category Id
         */
        category_id?: string | null;
    };
    url: '/tasks';
};

export type ListTasksTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTasksTasksGetError = ListTasksTasksGetErrors[keyof ListTasksTasksGetErrors];

export type ListTasksTasksGetResponses = {
    /**
     * Response List Tasks Tasks Get
     *
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type ListTasksTasksGetResponse = ListTasksTasksGetResponses[keyof ListTasksTasksGetResponses];

export type CreateTaskTasksPostData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type CreateTaskTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskTasksPostError = CreateTaskTasksPostErrors[keyof CreateTaskTasksPostErrors];

export type CreateTaskTasksPostResponses = {
    /**
     * Successful Response
     */
    201: TaskRead;
};

export type CreateTaskTasksPostResponse = CreateTaskTasksPostResponses[keyof CreateTaskTasksPostResponses];

export type DeleteTaskTasksTaskIdDeleteData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type DeleteTaskTasksTaskIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskTasksTaskIdDeleteError = DeleteTaskTasksTaskIdDeleteErrors[keyof DeleteTaskTasksTaskIdDeleteErrors];

export type DeleteTaskTasksTaskIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTaskTasksTaskIdDeleteResponse = DeleteTaskTasksTaskIdDeleteResponses[keyof DeleteTaskTasksTaskIdDeleteResponses];

export type ReadTaskTasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type ReadTaskTasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTaskTasksTaskIdGetError = ReadTaskTasksTaskIdGetErrors[keyof ReadTaskTasksTaskIdGetErrors];

export type ReadTaskTasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type ReadTaskTasksTaskIdGetResponse = ReadTaskTasksTaskIdGetResponses[keyof ReadTaskTasksTaskIdGetResponses];

export type UpdateTaskTasksTaskIdPatchData = {
    body: TaskUpdate;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type UpdateTaskTasksTaskIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTaskTasksTaskIdPatchError = UpdateTaskTasksTaskIdPatchErrors[keyof UpdateTaskTasksTaskIdPatchErrors];

export type UpdateTaskTasksTaskIdPatchResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type UpdateTaskTasksTaskIdPatchResponse = UpdateTaskTasksTaskIdPatchResponses[keyof UpdateTaskTasksTaskIdPatchResponses];

export type ListExperimentsExperimentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/experiments';
};

export type ListExperimentsExperimentsGetResponses = {
    /**
     * Response List Experiments Experiments Get
     *
     * Successful Response
     */
    200: Array<ExperimentRead>;
};

export type ListExperimentsExperimentsGetResponse = ListExperimentsExperimentsGetResponses[keyof ListExperimentsExperimentsGetResponses];

export type CreateExperimentExperimentsPostData = {
    body: ExperimentCreate;
    path?: never;
    query?: never;
    url: '/experiments';
};

export type CreateExperimentExperimentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateExperimentExperimentsPostError = CreateExperimentExperimentsPostErrors[keyof CreateExperimentExperimentsPostErrors];

export type CreateExperimentExperimentsPostResponses = {
    /**
     * Successful Response
     */
    201: ExperimentRead;
};

export type CreateExperimentExperimentsPostResponse = CreateExperimentExperimentsPostResponses[keyof CreateExperimentExperimentsPostResponses];

export type DeleteExperimentExperimentsExperimentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/experiments/{experiment_id}';
};

export type DeleteExperimentExperimentsExperimentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteExperimentExperimentsExperimentIdDeleteError = DeleteExperimentExperimentsExperimentIdDeleteErrors[keyof DeleteExperimentExperimentsExperimentIdDeleteErrors];

export type DeleteExperimentExperimentsExperimentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteExperimentExperimentsExperimentIdDeleteResponse = DeleteExperimentExperimentsExperimentIdDeleteResponses[keyof DeleteExperimentExperimentsExperimentIdDeleteResponses];

export type ReadExperimentExperimentsExperimentIdGetData = {
    body?: never;
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/experiments/{experiment_id}';
};

export type ReadExperimentExperimentsExperimentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadExperimentExperimentsExperimentIdGetError = ReadExperimentExperimentsExperimentIdGetErrors[keyof ReadExperimentExperimentsExperimentIdGetErrors];

export type ReadExperimentExperimentsExperimentIdGetResponses = {
    /**
     * Successful Response
     */
    200: ExperimentRead;
};

export type ReadExperimentExperimentsExperimentIdGetResponse = ReadExperimentExperimentsExperimentIdGetResponses[keyof ReadExperimentExperimentsExperimentIdGetResponses];

export type UpdateExperimentExperimentsExperimentIdPatchData = {
    body: ExperimentUpdate;
    path: {
        /**
         * Experiment Id
         */
        experiment_id: string;
    };
    query?: never;
    url: '/experiments/{experiment_id}';
};

export type UpdateExperimentExperimentsExperimentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateExperimentExperimentsExperimentIdPatchError = UpdateExperimentExperimentsExperimentIdPatchErrors[keyof UpdateExperimentExperimentsExperimentIdPatchErrors];

export type UpdateExperimentExperimentsExperimentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ExperimentRead;
};

export type UpdateExperimentExperimentsExperimentIdPatchResponse = UpdateExperimentExperimentsExperimentIdPatchResponses[keyof UpdateExperimentExperimentsExperimentIdPatchResponses];

export type ListWorkflowsWorkflowsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workflows';
};

export type ListWorkflowsWorkflowsGetResponses = {
    /**
     * Response List Workflows Workflows Get
     *
     * Successful Response
     */
    200: Array<WorkflowRead>;
};

export type ListWorkflowsWorkflowsGetResponse = ListWorkflowsWorkflowsGetResponses[keyof ListWorkflowsWorkflowsGetResponses];

export type CreateWorkflowWorkflowsPostData = {
    body: WorkflowCreate;
    path?: never;
    query?: never;
    url: '/workflows';
};

export type CreateWorkflowWorkflowsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWorkflowWorkflowsPostError = CreateWorkflowWorkflowsPostErrors[keyof CreateWorkflowWorkflowsPostErrors];

export type CreateWorkflowWorkflowsPostResponses = {
    /**
     * Successful Response
     */
    201: WorkflowRead;
};

export type CreateWorkflowWorkflowsPostResponse = CreateWorkflowWorkflowsPostResponses[keyof CreateWorkflowWorkflowsPostResponses];

export type DeleteWorkflowWorkflowsWorkflowIdDeleteData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/workflows/{workflow_id}';
};

export type DeleteWorkflowWorkflowsWorkflowIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkflowWorkflowsWorkflowIdDeleteError = DeleteWorkflowWorkflowsWorkflowIdDeleteErrors[keyof DeleteWorkflowWorkflowsWorkflowIdDeleteErrors];

export type DeleteWorkflowWorkflowsWorkflowIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteWorkflowWorkflowsWorkflowIdDeleteResponse = DeleteWorkflowWorkflowsWorkflowIdDeleteResponses[keyof DeleteWorkflowWorkflowsWorkflowIdDeleteResponses];

export type ReadWorkflowWorkflowsWorkflowIdGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/workflows/{workflow_id}';
};

export type ReadWorkflowWorkflowsWorkflowIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadWorkflowWorkflowsWorkflowIdGetError = ReadWorkflowWorkflowsWorkflowIdGetErrors[keyof ReadWorkflowWorkflowsWorkflowIdGetErrors];

export type ReadWorkflowWorkflowsWorkflowIdGetResponses = {
    /**
     * Successful Response
     */
    200: WorkflowRead;
};

export type ReadWorkflowWorkflowsWorkflowIdGetResponse = ReadWorkflowWorkflowsWorkflowIdGetResponses[keyof ReadWorkflowWorkflowsWorkflowIdGetResponses];

export type UpdateWorkflowWorkflowsWorkflowIdPatchData = {
    body: WorkflowUpdate;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/workflows/{workflow_id}';
};

export type UpdateWorkflowWorkflowsWorkflowIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWorkflowWorkflowsWorkflowIdPatchError = UpdateWorkflowWorkflowsWorkflowIdPatchErrors[keyof UpdateWorkflowWorkflowsWorkflowIdPatchErrors];

export type UpdateWorkflowWorkflowsWorkflowIdPatchResponses = {
    /**
     * Successful Response
     */
    200: WorkflowRead;
};

export type UpdateWorkflowWorkflowsWorkflowIdPatchResponse = UpdateWorkflowWorkflowsWorkflowIdPatchResponses[keyof UpdateWorkflowWorkflowsWorkflowIdPatchResponses];
